apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: $INFLUX_DB
    user: $INFLUX_USER
    url: http://influxdb:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: $INFLUX_PASSWORD
