version: '3.2'

services:
  influxdb:
    build: influxdb
    restart: always
    env_file: configuration.env
    ports:
      - '8086:8086'
      - '2003:2003'
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - monitor
  grafana:
    build: grafana
    restart: always
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitor

volumes:
  grafana_data: {}
  influxdb_data: {}

networks:
  monitor:
    driver: bridge
    name: monitor_network
