{
 "title": "Gatling",
 "description": "Visualize Grafana graphs based on Gatling benchmark results stored in Influxdb. Fully compatible with Docker.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "System",
     "select": [
      [
       { "params": [ "ProcessCpuLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Program" ], "type": "alias" }
      ],
      [
       { "params": [ "SystemCpuLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "heap used" ], "type": "alias" }
      ],
      [
       { "params": [ "HeapMemoryUsage_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "heap max" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "TPS all calls and Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Node $tag_request",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "gatling",
     "query": "SELECT count FROM \"gatling\" WHERE $timeFilter AND \"request\" != 'allRequests' AND \"status\"='all' group by request\n",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    },
    {
     "alias": "All req",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(count) FROM \"gatling\" WHERE $timeFilter AND \"request\" != 'allRequests' AND \"status\"='all' group by time(1s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling.users",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Moyenne 10s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(count) FROM \"gatling\" WHERE $timeFilter AND \"request\" != 'allRequests' AND \"status\"='all' group by time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg response times (50% Line)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_request",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT \"percentiles50\" FROM \"gatling\" WHERE (\"request\" <> 'allRequests') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" }
     ]
    }
   ]
  },
  {
   "title": "95 percentile response times (95% Line)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_request",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT \"percentiles95\" FROM \"gatling\" WHERE (\"request\" <> 'allRequests') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" }
     ]
    }
   ]
  },
  {
   "title": "Errors v Passes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "All Passes",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(count) FROM \"gatling\" WHERE $timeFilter AND (\"request\" != 'allRequests' AND \"status\" = 'ok') group by time(1s)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "All Errors",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(count) FROM \"gatling\" WHERE $timeFilter AND (\"request\" != 'allRequests' AND \"status\" = 'ko') group by time(1s)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "Pass $tag_request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count FROM \"gatling\" WHERE $timeFilter AND (\"request\" != 'allRequests' AND \"status\" = 'ok') group by request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Error $tag_request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count FROM \"gatling\" WHERE $timeFilter AND (\"request\" != 'allRequests' AND \"status\" = 'ko') group by request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "95th Percentile Response times cumulative",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "percentiles95",
     "measurement": "gatling",
     "query": "SELECT sum(\"percentiles95\") FROM \"gatling\" WHERE (\"request\" != 'allRequests' AND \"status\" = 'ok') AND $timeFilter group by time(1s)",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Latencies: Percentiles & Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "percentiles50",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(\"percentiles50\") FROM \"gatling\" WHERE (\"request\" != 'allRequests' AND \"status\" = 'ok') AND $timeFilter group by time(1s)",
     "select": [
      [
       { "params": [ "percentiles50" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "percentiles95",
     "measurement": "gatling",
     "query": "SELECT sum(\"percentiles95\") FROM \"gatling\" WHERE (\"request\" != 'allRequests' AND \"status\" = 'ok') AND $timeFilter group by time(1s)",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "percentiles99",
     "measurement": "gatling",
     "query": "SELECT sum(\"percentiles99\") FROM \"gatling\" WHERE (\"request\" != 'allRequests' AND \"status\" = 'ok') AND $timeFilter group by time(1s)",
     "select": [
      [
       { "params": [ "percentiles99" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    }
   ]
  }
 ]
}